# include "TH1.h"

// nominal cuts

TH1D * N1MCm22SUB2_pT[nbinsETA][ncentbins];
TH1D * N1MCp22SUB2_pT[nbinsETA][ncentbins];
TH1D * N1MCm22SUB3_pT[nbinsETA][ncentbins];
TH1D * N1MCp22SUB3_pT[nbinsETA][ncentbins];
TH1D * N1SUB2_pT[nbinsETA][ncentbins];
TH1D * N1ASUB2_pT[nbinsETA][ncentbins];
TH1D * N1BSUB2_pT[nbinsETA][ncentbins];
TH1D * N112SUB2_pT[nbinsETA][ncentbins];
TH1D * N112ASUB2_pT[nbinsETA][ncentbins];
TH1D * N112BSUB2_pT[nbinsETA][ncentbins];
TH1D * N1SUB3_pT[nbinsETA][ncentbins];
TH1D * N1ASUB3_pT[nbinsETA][ncentbins];
TH1D * N1BSUB3_pT[nbinsETA][ncentbins];

TH1D * N1MCm22SUB2_eta[ncentbins];
TH1D * N1MCp22SUB2_eta[ncentbins];
TH1D * N1MC22SUB2_eta[ncentbins];
TH1D * N1MCm22SUB3_eta[ncentbins];
TH1D * N1MCp22SUB3_eta[ncentbins];
TH1D * N1MC22SUB3_eta[ncentbins];
TH1D * N1SUB2_eta[ncentbins];
TH1D * N1ASUB2_eta[ncentbins];
TH1D * N1BSUB2_eta[ncentbins];
TH1D * N112SUB2_eta[ncentbins];
TH1D * N112ASUB2_eta[ncentbins];
TH1D * N112BSUB2_eta[ncentbins];
TH1D * N1SUB3_eta[ncentbins];
TH1D * N1ASUB3_eta[ncentbins];
TH1D * N1BSUB3_eta[ncentbins];

// tight cuts

TH1D * N1MCm22SUB2_tight_pT[nbinsETA][ncentbins];
TH1D * N1MCp22SUB2_tight_pT[nbinsETA][ncentbins];
TH1D * N1MCm22SUB3_tight_pT[nbinsETA][ncentbins];
TH1D * N1MCp22SUB3_tight_pT[nbinsETA][ncentbins];
TH1D * N1SUB2_tight_pT[nbinsETA][ncentbins];
TH1D * N1ASUB2_tight_pT[nbinsETA][ncentbins];
TH1D * N1BSUB2_tight_pT[nbinsETA][ncentbins];
TH1D * N112SUB2_tight_pT[nbinsETA][ncentbins];
TH1D * N112ASUB2_tight_pT[nbinsETA][ncentbins];
TH1D * N112BSUB2_tight_pT[nbinsETA][ncentbins];
TH1D * N1SUB3_tight_pT[nbinsETA][ncentbins];
TH1D * N1ASUB3_tight_pT[nbinsETA][ncentbins];
TH1D * N1BSUB3_tight_pT[nbinsETA][ncentbins];

TH1D * N1MCm22SUB2_tight_eta[ncentbins];
TH1D * N1MCp22SUB2_tight_eta[ncentbins];
TH1D * N1MC22SUB2_tight_eta[ncentbins];
TH1D * N1MCm22SUB3_tight_eta[ncentbins];
TH1D * N1MCp22SUB3_tight_eta[ncentbins];
TH1D * N1MC22SUB3_tight_eta[ncentbins];
TH1D * N1SUB2_tight_eta[ncentbins];
TH1D * N1ASUB2_tight_eta[ncentbins];
TH1D * N1BSUB2_tight_eta[ncentbins];
TH1D * N112SUB2_tight_eta[ncentbins];
TH1D * N112ASUB2_tight_eta[ncentbins];
TH1D * N112BSUB2_tight_eta[ncentbins];
TH1D * N1SUB3_tight_eta[ncentbins];
TH1D * N1ASUB3_tight_eta[ncentbins];
TH1D * N1BSUB3_tight_eta[ncentbins];

// wide cuts

TH1D * N1MCm22SUB2_wide_pT[nbinsETA][ncentbins];
TH1D * N1MCp22SUB2_wide_pT[nbinsETA][ncentbins];
TH1D * N1MCm22SUB3_wide_pT[nbinsETA][ncentbins];
TH1D * N1MCp22SUB3_wide_pT[nbinsETA][ncentbins];
TH1D * N1SUB2_wide_pT[nbinsETA][ncentbins];
TH1D * N1ASUB2_wide_pT[nbinsETA][ncentbins];
TH1D * N1BSUB2_wide_pT[nbinsETA][ncentbins];
TH1D * N112SUB2_wide_pT[nbinsETA][ncentbins];
TH1D * N112ASUB2_wide_pT[nbinsETA][ncentbins];
TH1D * N112BSUB2_wide_pT[nbinsETA][ncentbins];
TH1D * N1SUB3_wide_pT[nbinsETA][ncentbins];
TH1D * N1ASUB3_wide_pT[nbinsETA][ncentbins];
TH1D * N1BSUB3_wide_pT[nbinsETA][ncentbins];

TH1D * N1MCm22SUB2_wide_eta[ncentbins];
TH1D * N1MCp22SUB2_wide_eta[ncentbins];
TH1D * N1MC22SUB2_wide_eta[ncentbins];
TH1D * N1MCm22SUB3_wide_eta[ncentbins];
TH1D * N1MCp22SUB3_wide_eta[ncentbins];
TH1D * N1MC22SUB3_wide_eta[ncentbins];
TH1D * N1SUB2_wide_eta[ncentbins];
TH1D * N1ASUB2_wide_eta[ncentbins];
TH1D * N1BSUB2_wide_eta[ncentbins];
TH1D * N112SUB2_wide_eta[ncentbins];
TH1D * N112ASUB2_wide_eta[ncentbins];
TH1D * N112BSUB2_wide_eta[ncentbins];
TH1D * N1SUB3_wide_eta[ncentbins];
TH1D * N1ASUB3_wide_eta[ncentbins];
TH1D * N1BSUB3_wide_eta[ncentbins];

// narrow cuts

TH1D * N1MCm22SUB2_narrow_pT[nbinsETA][ncentbins];
TH1D * N1MCp22SUB2_narrow_pT[nbinsETA][ncentbins];
TH1D * N1MCm22SUB3_narrow_pT[nbinsETA][ncentbins];
TH1D * N1MCp22SUB3_narrow_pT[nbinsETA][ncentbins];
TH1D * N1SUB2_narrow_pT[nbinsETA][ncentbins];
TH1D * N1ASUB2_narrow_pT[nbinsETA][ncentbins];
TH1D * N1BSUB2_narrow_pT[nbinsETA][ncentbins];
TH1D * N112SUB2_narrow_pT[nbinsETA][ncentbins];
TH1D * N112ASUB2_narrow_pT[nbinsETA][ncentbins];
TH1D * N112BSUB2_narrow_pT[nbinsETA][ncentbins];
TH1D * N1SUB3_narrow_pT[nbinsETA][ncentbins];
TH1D * N1ASUB3_narrow_pT[nbinsETA][ncentbins];
TH1D * N1BSUB3_narrow_pT[nbinsETA][ncentbins];

TH1D * N1MCm22SUB2_narrow_eta[ncentbins];
TH1D * N1MCp22SUB2_narrow_eta[ncentbins];
TH1D * N1MC22SUB2_narrow_eta[ncentbins];
TH1D * N1MCm22SUB3_narrow_eta[ncentbins];
TH1D * N1MCp22SUB3_narrow_eta[ncentbins];
TH1D * N1MC22SUB3_narrow_eta[ncentbins];
TH1D * N1SUB2_narrow_eta[ncentbins];
TH1D * N1ASUB2_narrow_eta[ncentbins];
TH1D * N1BSUB2_narrow_eta[ncentbins];
TH1D * N112SUB2_narrow_eta[ncentbins];
TH1D * N112ASUB2_narrow_eta[ncentbins];
TH1D * N112BSUB2_narrow_eta[ncentbins];
TH1D * N1SUB3_narrow_eta[ncentbins];
TH1D * N1ASUB3_narrow_eta[ncentbins];
TH1D * N1BSUB3_narrow_eta[ncentbins];


// absolute difference plots

TH1D * diff_N1MCm22SUB2_nom_tight_pT[nbinsETA][ncentbins];
TH1D * diff_N1MCp22SUB2_nom_tight_pT[nbinsETA][ncentbins];
TH1D * diff_N1MCm22SUB3_nom_tight_pT[nbinsETA][ncentbins];
TH1D * diff_N1MCp22SUB3_nom_tight_pT[nbinsETA][ncentbins];
TH1D * diff_N1SUB2_nom_tight_pT[nbinsETA][ncentbins];
TH1D * diff_N1ASUB2_nom_tight_pT[nbinsETA][ncentbins];
TH1D * diff_N1BSUB2_nom_tight_pT[nbinsETA][ncentbins];
TH1D * diff_N112SUB2_nom_tight_pT[nbinsETA][ncentbins];
TH1D * diff_N112ASUB2_nom_tight_pT[nbinsETA][ncentbins];
TH1D * diff_N112BSUB2_nom_tight_pT[nbinsETA][ncentbins];
TH1D * diff_N1SUB3_nom_tight_pT[nbinsETA][ncentbins];
TH1D * diff_N1ASUB3_nom_tight_pT[nbinsETA][ncentbins];
TH1D * diff_N1BSUB3_nom_tight_pT[nbinsETA][ncentbins];

TH1D * diff_N1MCm22SUB2_nom_tight_eta[ncentbins];
TH1D * diff_N1MCp22SUB2_nom_tight_eta[ncentbins];
TH1D * diff_N1MC22SUB2_nom_tight_eta[ncentbins];
TH1D * diff_N1MCm22SUB3_nom_tight_eta[ncentbins];
TH1D * diff_N1MCp22SUB3_nom_tight_eta[ncentbins];
TH1D * diff_N1MC22SUB3_nom_tight_eta[ncentbins];
TH1D * diff_N1SUB2_nom_tight_eta[ncentbins];
TH1D * diff_N1ASUB2_nom_tight_eta[ncentbins];
TH1D * diff_N1BSUB2_nom_tight_eta[ncentbins];
TH1D * diff_N112SUB2_nom_tight_eta[ncentbins];
TH1D * diff_N112ASUB2_nom_tight_eta[ncentbins];
TH1D * diff_N112BSUB2_nom_tight_eta[ncentbins];
TH1D * diff_N1SUB3_nom_tight_eta[ncentbins];
TH1D * diff_N1ASUB3_nom_tight_eta[ncentbins];
TH1D * diff_N1BSUB3_nom_tight_eta[ncentbins];

TH1D * diff_N1MCm22SUB2_nom_wide_pT[nbinsETA][ncentbins];
TH1D * diff_N1MCp22SUB2_nom_wide_pT[nbinsETA][ncentbins];
TH1D * diff_N1MCm22SUB3_nom_wide_pT[nbinsETA][ncentbins];
TH1D * diff_N1MCp22SUB3_nom_wide_pT[nbinsETA][ncentbins];
TH1D * diff_N1SUB2_nom_wide_pT[nbinsETA][ncentbins];
TH1D * diff_N1ASUB2_nom_wide_pT[nbinsETA][ncentbins];
TH1D * diff_N1BSUB2_nom_wide_pT[nbinsETA][ncentbins];
TH1D * diff_N112SUB2_nom_wide_pT[nbinsETA][ncentbins];
TH1D * diff_N112ASUB2_nom_wide_pT[nbinsETA][ncentbins];
TH1D * diff_N112BSUB2_nom_wide_pT[nbinsETA][ncentbins];
TH1D * diff_N1SUB3_nom_wide_pT[nbinsETA][ncentbins];
TH1D * diff_N1ASUB3_nom_wide_pT[nbinsETA][ncentbins];
TH1D * diff_N1BSUB3_nom_wide_pT[nbinsETA][ncentbins];

TH1D * diff_N1MCm22SUB2_nom_wide_eta[ncentbins];
TH1D * diff_N1MCp22SUB2_nom_wide_eta[ncentbins];
TH1D * diff_N1MC22SUB2_nom_wide_eta[ncentbins];
TH1D * diff_N1MCm22SUB3_nom_wide_eta[ncentbins];
TH1D * diff_N1MCp22SUB3_nom_wide_eta[ncentbins];
TH1D * diff_N1MC22SUB3_nom_wide_eta[ncentbins];
TH1D * diff_N1SUB2_nom_wide_eta[ncentbins];
TH1D * diff_N1ASUB2_nom_wide_eta[ncentbins];
TH1D * diff_N1BSUB2_nom_wide_eta[ncentbins];
TH1D * diff_N112SUB2_nom_wide_eta[ncentbins];
TH1D * diff_N112ASUB2_nom_wide_eta[ncentbins];
TH1D * diff_N112BSUB2_nom_wide_eta[ncentbins];
TH1D * diff_N1SUB3_nom_wide_eta[ncentbins];
TH1D * diff_N1ASUB3_nom_wide_eta[ncentbins];
TH1D * diff_N1BSUB3_nom_wide_eta[ncentbins];

TH1D * diff_N1MCm22SUB2_nom_narrow_pT[nbinsETA][ncentbins];
TH1D * diff_N1MCp22SUB2_nom_narrow_pT[nbinsETA][ncentbins];
TH1D * diff_N1MCm22SUB3_nom_narrow_pT[nbinsETA][ncentbins];
TH1D * diff_N1MCp22SUB3_nom_narrow_pT[nbinsETA][ncentbins];
TH1D * diff_N1SUB2_nom_narrow_pT[nbinsETA][ncentbins];
TH1D * diff_N1ASUB2_nom_narrow_pT[nbinsETA][ncentbins];
TH1D * diff_N1BSUB2_nom_narrow_pT[nbinsETA][ncentbins];
TH1D * diff_N112SUB2_nom_narrow_pT[nbinsETA][ncentbins];
TH1D * diff_N112ASUB2_nom_narrow_pT[nbinsETA][ncentbins];
TH1D * diff_N112BSUB2_nom_narrow_pT[nbinsETA][ncentbins];
TH1D * diff_N1SUB3_nom_narrow_pT[nbinsETA][ncentbins];
TH1D * diff_N1ASUB3_nom_narrow_pT[nbinsETA][ncentbins];
TH1D * diff_N1BSUB3_nom_narrow_pT[nbinsETA][ncentbins];

TH1D * diff_N1MCm22SUB2_nom_narrow_eta[ncentbins];
TH1D * diff_N1MCp22SUB2_nom_narrow_eta[ncentbins];
TH1D * diff_N1MC22SUB2_nom_narrow_eta[ncentbins];
TH1D * diff_N1MCm22SUB3_nom_narrow_eta[ncentbins];
TH1D * diff_N1MCp22SUB3_nom_narrow_eta[ncentbins];
TH1D * diff_N1MC22SUB3_nom_narrow_eta[ncentbins];
TH1D * diff_N1SUB2_nom_narrow_eta[ncentbins];
TH1D * diff_N1ASUB2_nom_narrow_eta[ncentbins];
TH1D * diff_N1BSUB2_nom_narrow_eta[ncentbins];
TH1D * diff_N112SUB2_nom_narrow_eta[ncentbins];
TH1D * diff_N112ASUB2_nom_narrow_eta[ncentbins];
TH1D * diff_N112BSUB2_nom_narrow_eta[ncentbins];
TH1D * diff_N1SUB3_nom_narrow_eta[ncentbins];
TH1D * diff_N1ASUB3_nom_narrow_eta[ncentbins];
TH1D * diff_N1BSUB3_nom_narrow_eta[ncentbins];
